version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "auth_DB"
      POSTGRES_USER: "amogus"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - auth_data:/var/lib/postgresql/data/pgdata
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "2750:5432"
    networks:
      - dev

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amogus -d auth_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  auth_data:

networks:
  dev: